apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "passbolt.fullname" . }}-config-mysql
data:
{{- range $key, $val := .Values.configMYSQL }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}