{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.type }}
  {{- range .Values.ingress.annotations }}
    {{ . }}
  {{- end }}
  name: {{ template "passbolt.fullname" . }}
  labels:
    chart: {{ template "passbolt.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  tls:
  - hosts:
    - passbolt.{{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.sslSecret }}
  rules:
    - host: passbolt.{{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ template "passbolt.fullname" . }}
              servicePort: 443
            path: /
{{- end }}