apiVersion: v1
kind: Secret
metadata:
  name: {{ include "passbolt-helm.fullname" . }}-gpg
  labels:
{{ include "passbolt-helm.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  "serverkey.asc": {{ if .Values.passbolt.config.serverkey }}{{ .Values.passbolt.config.serverkey | b64enc | quote }}{{ else }}{{ .Files.Get "secrets/gpg/serverkey.asc" | b64enc | quote }}{{ end }}
  "serverkey_private.asc": {{ if .Values.passbolt.config.serverkey_private }}{{ .Values.passbolt.config.serverkey_private | b64enc | quote }}{{ else }}{{ .Files.Get "secrets/gpg/serverkey_private.asc" | b64enc | quote }}{{ end }}